apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-gfg
  namespace: gfg
spec:
  containers:
  - name: demo-container
    image: nginx
    envFrom:
    - configMapRef:
       name: configmap-gfg